[versions]
accompanist = "0.24.9-beta"
compose = "1.1.0-beta01"
kotlin = "1.5.31"
android-gradle-plugin = "7.2.1"
androidx-core = "1.7.0"
androidx-appcompat = "1.3.1"
google-material = "1.4.0"
test-junit = "4.13.2"
androidx-test-junit = "1.1.3"
androidx-test-espresso = "3.4.0"
coil = "2.1.0"
hilt = "2.38.1"
retrofit = "2.9.0"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }

coroutine = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.3"

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-kapt = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
moshi-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.3.1"
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }

google-material = { module = "com.google.android.material:material", version.ref = "google-material" }

test-junit = { module = "junit:junit", version.ref = "test-junit" }

accompanist-navigation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-systemui = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-tool = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-test = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-navigation = "androidx.navigation:navigation-compose:2.4.2"
compose-activity = "androidx.activity:activity-compose:1.3.1"

coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

[bundles]
android = [
    "androidx-core",
    "androidx-appcompat",
    "androidx-lifecycle",
    "google-material"
]
compose = [
    "compose-ui",
    "compose-material",
    "compose-tooling-preview",
    "compose-activity",
    "compose-navigation",
    "accompanist-navigation"
]